package com.chl.MBG.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.id
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.name
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.gender
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.dept_id
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.id
     *
     * @return the value of mybatis.id
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.id
     *
     * @param id the value for mybatis.id
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.name
     *
     * @return the value of mybatis.name
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.name
     *
     * @param name the value for mybatis.name
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.gender
     *
     * @return the value of mybatis.gender
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.gender
     *
     * @param gender the value for mybatis.gender
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.dept_id
     *
     * @return the value of mybatis.dept_id
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.dept_id
     *
     * @param deptId the value for mybatis.dept_id
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}