package com.chl.MBG.dao;

import com.chl.MBG.bean.User;
import com.chl.MBG.bean.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis
     *
     * @mbg.generated Mon Dec 28 10:24:29 CST 2020
     */
    int updateByPrimaryKey(User record);
}